---
title: "Heat Transfer in Tube Furnace for Semiconductors"
author: "Mailey"
date: "2025-11-24"
categories: [PDE]
---

The objective of the project is to determine the temperature profile laterally along a cylindrical tube furnace when specific parameters for conduction and radiation are given. There is an existing paper on this heat transfer model with plotted lateral temperature profiles that can used to reference for verification and validation. To simplify this to be easier to compute, there will be specific parameters defined for the dimensions of the tube furnace. There will also be some boundary conditions in place to make the temperature profile match more closely to the paper's temperature plot such as having the walls (at a certain distance x and radius r) having a hotter temperature and the top and bottom surfaces of the tube furnace to be cooler. This way, the middle furnace section should be displayed as the hottest and the rest of the furnace would cool in a symmetric manner. With those parameters in mind, plotting the lateral temperature profile should fall into place as long as the correct numerical methods are chosen for the heat transfer (the paper mentions using trapezoidal rule).

This model and problem is meant to demonstrate the proper temperature that's suitable for semiconductor crystal growth. The computational component comes from implementing the equations for conduction and radiation from the paper and plotting the temperature versus the lateral length of the tube furnace as distance x. It's computational in how heat transfer is a partial differential equation type of phenomenon, which calls for iterative and numerical methods. This is particularly appealing to me because I am more used to seeing this problem through an engineering lens but hopefully with this physics project, I can gain more understanding to modelling this problem, as this is based off a real task that an established semiconductor fabrication company is undertaking.

The expected results should be some sort of temperature plot of the lateral temperature profile of the tube furnace. The total heat flux can be calculated from a differential equation on conduction that may be combined with a specific radiation equation. Please note that there may be some minor changes to simplify the model to be more doable. There is an equation to be looked at in the research paper being referenced for this design project but there is another conduction equation to be considered in the class textbook in chapter 14. 

The question to be answered is what is the lateral temperature profile of the tube furnace based on the given parameters for conduction and radiation heat transfer involved. There is in fact comparable data that can be referenced from this paper on ["Modelling Temperature Distribution in Cylindrical Crystal Growth Furnaces"](https://doi.org/10.1016/0735-1933(96)00023-1). The data to be used in comparison is the middle curve in Figure 2a, where the chosen heat flux is $q = 0.1431 W/cm^2$. In section a of Figure 2, the chosen dimensions of the tube furnace was $L = 20 cm$ and $D = 2.5 cm$. It's to be expected that the middle section of the tube furnace be the hottest and the bottom and top ends as the coldest, making a parabolic shape as the temperature profile.